# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
before_install: 
  - sudo apt-get install cmake
  - sudo apt-get install libgtest-dev
  - export GTEST_ROOT=/usr/src/gtest
language: cpp
compiler:
  - clang
script:
  - mkdir _builds
  - cd _builds
  - cmake ..
  - make
  - ctest

#script: cmake -DJSONCPP_LIB_BUILD_SHARED=$SHARED_LIBRARY -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_VERBOSE_MAKEFILE=$VERBOSE_MAKE . && make
#env:
#  global:
#    - JSONCPP_CONTINUOUS_INTERATION=1
#  matrix:
#    - SHARED_LIBRARY=ON BUILD_TYPE=release VERBOSE_MAKE=false
#    - SHARED_LIBRARY=OFF BUILD_TYPE=release VERBOSE_MAKE=false
#    - SHARED_LIBRARY=OFF BUILD_TYPE=debug VERBOSE VERBOSE_MAKE=true
notifications:
  recipients:
    - nicolas.martin@arobas-music.com
  email:
    on_success: change
    on_failure: always